// This file will be auto-generated by Amplify when you deploy
// For now, we'll create a placeholder that will be replaced
export default {
  aws_project_region: 'us-east-1',
  aws_appsync_graphqlEndpoint: 'https://placeholder.appsync-api.us-east-1.amazonaws.com/graphql',
  aws_appsync_region: 'us-east-1',
  aws_appsync_authenticationType: 'API_KEY',
  aws_appsync_apiKey: 'placeholder-api-key',
};
